We shouldn't override PostgreSQLAdapter's superclass inheritance while monkeypatching
Changing Inheritance section leads to following error on JRuby

    TypeError: superclass mismatch for class PostgreSQLAdapter

After this change,
Jruby: The above error no longer appear. Tests are still failing but they do run. Progress!
MRI: No change, all green(tested by running take test_test_postgresql)

Thanks to Aditya Sanghi(@asanghi) for help