`AC::TestCase` can teardown gracefully if setup errors early.
If for some reason a setup callback raised an error before
`ActionController::TestCase` was able to setup it's subscribers,
another error would be raised:

        NoMethodError: undefined method `each' for nil:NilClass

This was especially cumbersome because that error shadowed the original error
in the setup chain.

This would lead to obscure errors. For example a fixture containing bad data
could lead to the following test backtrace:

```
Error:
ArticlesControllerTest#test_should_get_edit:
NoMethodError: undefined method `each' for nil:NilClass
    /Users/senny/Projects/rails/actionpack/lib/action_controller/test_case.rb:60:in `teardown_subscriptions'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:432:in `block in make_lambda'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:263:in `call'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:263:in `block in simple'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:506:in `call'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:506:in `block in call'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:506:in `each'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:506:in `call'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:778:in `_run_teardown_callbacks'
    /Users/senny/Projects/rails/activesupport/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /Users/senny/Projects/rails/activesupport/lib/active_support/testing/setup_and_teardown.rb:45:in `after_teardown'
    /Users/senny/Projects/rails/activerecord/lib/active_record/fixtures.rb:831:in `after_teardown'
```