Add more specific Ruby/Rails version information
Since the upgrade path from older versions will often take people
through Rails 4.0 and they will often use the latest Ruby, this warning
about incompatible versions can save a lot of time during an upgrade.

The error you get with ActiveRecord 4.0 and Ruby 2.2 is inexplicable:

undefined method `name' for nil:NilClass
  activerecord-4.0.0/lib/active_record/associations/has_many_association.rb:80:in `cached_counter_attribute_name'

[ci skip]