Fix an incorrect example in the doc of the Strong Parameters [ci skip]
This PR fixes an incorrect example in the doc of the Strong Parameters.

Calling `permitted?` on an array object will raise a `NoMethodError`:

```ruby
params = ActionController::Parameters.new(tags: ["rails", "parameters"])
# => #<ActionController::Parameters {"tags"=>["rails", "parameters"]} permitted: false>

permitted = params.expect(tags: [])
# => ["rails", "parameters"]

permitted.permitted?
# => undefined method `permitted?' for an instance of Array (NoMethodError)
```

In the documentation example, the value of the `permitted` variable is explicitly shown instead.