Requires ActionView::Helpers::TagHelper deps
It turns out that TagHelper depends on additional view helpers, as well
as ActiveSupport::Concern. This isn't explicitly required because when
Rails is loaded all at once, these constants will have been required
elsewhere, but it's necessary to declare the dependency explicitly if
anyone is going to require something from ActionView directly.

I stumbled upon this because I was trying to require just DateHelper:

> require "action_view/helpers/date_helper"
NameError: uninitialized constant ActiveSupport::Concern
from …rails/actionview/lib/action_view/helpers/tag_helper.rb:12:in `<module:TagHelper>'