Ensure connection is removed after ConnectionHandlersShardingDbTest   test_establish_connection_using_3_levels_config_with_shards_and_replica
```
Error:
ActiveRecord::ConnectionAdapters::ConnectionHandlersShardingDbTest#test_establishing_a_connection_in_connected_to_block_uses_current_role_and_shard:
RuntimeError: Connections leaked
[#<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x00000000129ab0 env_name="arunit" role=:writing shard=:shard_one>]
    test/cases/test_case.rb:58:in 'ActiveRecord::TestCase#after_teardown'
bin/rails test /rails/activerecord/test/cases/connection_adapters/connection_handlers_sharding_db_test.rb:18
```