Store the symbols as an array.
A Set can't be implicitly converted into an Array:

```
irb(main):012:0> formats = [ :rss ]
=> [:rss]
irb(main):013:0> formats &= SET.symbols
TypeError: no implicit conversion of Set into Array
    from (irb):13:in `&'
    from (irb):13
    from /Users/kasperhansen/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```

Besides `Mime::SET.symbols` returns an Array, so we're closer to that.