Remove invalid tests in config
These were accidentally added in
cb1a753d91f6092c26a2a130229369666172563d when
https://github.com/rails/rails/pull/45293 was backported to 7-0-stable.

This config isn't available in 7.0 so these tests were failing with
`NoMethodError: undefined method `log_file_size'`.