Revert "Merge pull request #9206 from ranjaykrishna/use_define_method"
This reverts commit 1fc6876b57f2e1d31731e74eb4271b5655e746d2, reversing
changes made to 0268b5d8cdc3c5a1337462135f0a326a2654ba1a.

Reason: failing test

  1) Error:
test_valid_column(ActiveRecord::ConnectionAdapters::SQLite3AdapterTest):
NoMethodError: undefined method `column' for
    test/cases/adapters/sqlite3/sqlite3_adapter_test.rb:29:in
`test_valid_column'