Fix NameError in Mysql2::DatabaseStatements
The recent [refactor][1] to the MySQL DatabaseStatements classes renamed
Mysql::DatabaseStatements to Mysql2::DatabaseStatements. That commit
also updated most of the references to the top level Mysql2 to be
explicit since Ruby will now assume they refer to
ActiveRecord::ConnectionAdapters::Mysql2. However, Mysql2::Error was not
updated, and that rescue will currently raise:

```
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::Mysql2::Error
```

if the execute raises any error.

To fix this, Mysql2 must be changed to explicitly refer to the top level
namespace.

[1]: 93b5fc1f95e04b6a51f3e8dd2c885ba9ddd139a6