Provide more help when a rails runner file argument does not exist.
Previously, rails runner would boot the rails application and process
the argument to runner in two distinct ways:

* If the argument was an existing file, it would load the file as a
ruby script.

* Otherwise, the arguments are treated as in-line ruby and are
evaluated.

If a user mistakenly provided rails runner a wrong path to a script,
the error was very confusing.

This commit handles the two common situations I can envision:

1) User provides a missing path with a leading slash: /home/joe/run.rb.
Previously, this would fail with an strange `unknown regexp option`
SyntaxError because the slash is treated as a regexp.

2) User provides a missing path without a leading slash: joe/run.rb.
Previously, this would fail with a `NameError` because `joe` would not
be defined.

This commit detects both situations, discards the backtrace since it
is probaly not useful for a in-line ruby argument passed to rails
runner, prints a more friendly warning and exits 1.

Below are some examples of the two situations before and after:

1) User provides a missing path with a leading slash: /home/joe/run.rb.

```
$ bin/rails r "/home/joe/run.rb"
~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/runner.rb:63:in `eval': ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/runner.rb:63: unknown regexp option - j (SyntaxError)
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/runner.rb:63:in `<top (required)>'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:90:in `runner'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
$ echo $?
1

```

With fix:

```
$ bin/rails r "/home/joe/run.rb"
The argument to runner was evaluated as ruby with a SyntaxError: '/home/joe/run.rb'.
    If this is a file, please verify the file exists and is readable.
$ echo $?
1
```

2) User provides a missing path without a leading slash: joe/run.rb.

```
$  bin/rails r "joe/run.rb"
~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/runner.rb:63:in `<top (required)>': undefined local variable or method `joe' for main:Object (NameError)
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/runner.rb:63:in `eval'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/runner.rb:63:in `<top (required)>'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:90:in `runner'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from ~/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
$ echo $?
1
```

With fix:

```
$ bin/rails r "joe/run.rb"
The argument to runner was evaluated as ruby with a NameError: 'joe/run.rb'.
    If this is a file, please verify the file exists and is readable.
$ echo $?
1
```