Fix problem with accessing constant proxy subclass
This commit fixes #36313.

After #32065 moved `SourceAnnotationExtractor` into `Rails` module, it
broke the ability to access `SourceAnnotationExtractor::Annotate`
directly as user would get this error:

    TypeError: Rails::SourceAnnotationExtractor is not a class/module

This commit fixes the issue by making `DeprecatedConstantProxy` to
inherit from `Module` and then defines `method_missing` and
`const_missing` to retain the previous functionality.

Thank you Matthew Draper for the idea of how to fix the issue!

[Prem Sichanugrist & Matthew Draper]