test with latest resque
When run test of Active Job with resque 1.26, occurs following error.

```
QueuingTest#test_current_locale_is_kept_while_running_perform_later:
NoMethodError: undefined method `current_tags' for #<Resque::QuietFormatter:0x0055b44f63ed50>
    /home/yaginuma/program/rails/master_y_yagi/rails/activejob/lib/active_job/logging.rb:51:in `logger_tagged_by_active_job?'
```

This was happening for the formatter class of resque not the formatter class of
Rails is they've been used to logger.formatter.
This was happening because become fomatter is changed during the instantiation
of worker in the resque 1.26.
In the master, unless the environment variable is set, fomatter is so as not to
be changed, test will pass.

Ref: https://github.com/resque/resque/pull/1439