Extend `ActiveSupport::StringInquirer` to specify valid values
`StringInquirer` now supports specifying which values are valid so that
only a specific set of *inquiries* can be called on it. Example:

```ruby
class Offer < Struct.new(:status)
  VALID_STATUSES = %w(pending active finished)

  def status
    super.inquiry(restricted_to: VALID_STATUSES)
  end
end

> Offer.new('pending').status.pending?
=> true

> Offer.new('finished').status.active?
=> false

> Offer.new('ended').status.ended?
NoMethodError: undefined method `ended?` for "ended":ActiveSupport::StringInquirer

> Offer.new('active').status.valid_values
=> ["pending", "active", "finished"]
```

Current existing behavior of `StringInquiry` is preserved if a list of
valid values is not specified:

```ruby
> 'pending'.inquiry.pending?
=> true

> 'active'.inquiry.whaaat?
=> false
```