[5-0-stable] Add support for Minitest 5.11
  Merge pull request #31624 from y-yagi/fix_minitest_511
  Add support for Minitest 5.11
  cherry-pick 0552bcab646de4b8bdacf37823449a7c58431c2c

  `Minitest::Result` can't use in 5-0-stable
  Because Minitest is locked by 5.3.3.
  cherry-pick f7e5f19fb38d298132f27500a354e0638e4ce762

Fixes
```
rails/railties/lib/rails/test_unit/reporter.rb:70:in `method':
undefined method `test_the_truth' for class `Minitest::Result' (NameError)
```

Related to https://github.com/seattlerb/minitest/issues/730