Update min Ruby version
When installing Rails 8.0.0.beta, I found that I needed to have Ruby >= 3.2., but the edge guides mention 3.1.

```
% gem install rails --version 8.0.0.beta1
ERROR:  Error installing rails:
	rails-8.0.0.beta1 requires Ruby version >= 3.2.0. The current ruby version is 3.1.3.
```