Modified ActiveSupport::Inflector#safe_constantize to handle the case where a NameError is raised for something other than the specified String; modified ActiveSupport::Inflector#constantized to ensure that when it raises a NameError sets the name to be the value of the specified String (this is needed for the change to ActiveSupport::Inflector#safe_constantize to work); cleaned up multiple definitions of ActiveSupport::Inflector#constantized