Ensure #pluck behaves consistently across types
As it's currently written, Enumerable#pluck behaves inconsistently when
working with Hashes (as in the method's documentation), with Structs
(which are used in the method's tests), and with ActiveRecord models
(Enumerable#pluck is meant to emulate ActiveRecord::Calculations#pluck)
when a given key is not present or, in the case of a Hash, when `nil` is not the
Hash's default value.

Per @dhh's notes on Issue #20339, I take the return behavior of
`ActiveRecord::Base#[]` as the reference behavior: namely, a key not
present in an element should return `nil` rather than raising an
exception (as occurs when calling #pluck with an unfamiliar attribute on
an AR relation):

```
[38] pry(main)> users.pluck(:names)
PG::UndefinedColumn: ERROR:  column "names" does not exist
```

```
[52] pry(main)> user.class
=> User(id: integer, email: string...
[51] pry(main)> user[:names]
=> nil
```

```
[3] pry(main)> user = Hash.new('!'); user[:email] = 'email@example.com'
[6] pry(main)> user[:names]
"!"
```

```
[59] pry(main)> User = Struct.new(:email)
[60] pry(main)> User.new('user@example.com')
[63] pry(main)> user[:names]
NameError: no member 'names' in struct
        from: (pry):63:in `[]'
```

This patch makes the method's behavior consistent across types,
normalizing on the behavior of `ActiveRecord::Base#[]` while adding
two further benefits:

1. Makes it robust to Hash objects with non-nil default values
2. Enables it to work on mixed collections

Related:
[Issue #20339][20339]
[PR #20350][20350]

[20339]: https://github.com/rails/rails/issues/20339
[20350]: https://github.com/rails/rails/pull/20350