Require deprecator in core_exts that use it
Currently, requiring a railtie file that defines configuration options
would cause error:

```rb
require "rails/railtie"

class Foo < Rails::Railtie
  config.foo = ActiveSupport::OrderedOptions.new
  config.foo.greetings = "hello"
end
```

```
/PATH_TO_BUNDLER/gems/rails-f9e4fb9bedec/activesupport/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
```

Essentially, the problem is that `active_support/deprecator` is not
required in the core_ext files that use it.

And consider core ext files are usually required individually, I think
it's better to require `active_support/deprecator` in the core_ext files
instead of in `rails/railtie`.

And given that `active_support/deprecator` would not work without `active_support/deprecation`,
I think it's better to require `active_support/deprecation` in it.