Only emit logs if logger is defined
See https://github.com/rails/rails/pull/56213#issuecomment-3642535238

Fixes the following error on main:

1. First generate a new Rails app:

```sh
rails/railties/exe/rails new issue56230 --dev
cd issue56230/
RAILS_ENV=production RAILS_LOG_LEVEL=debug bin/rails server
```

Then edit config/environments/production.rb replacing these lines:

```diff
-  config.consider_all_requests_local = false
+  config.consider_all_requests_local = true

+  config.action_view.logger = nil
```

Then open http://localhost:3000/up in the browser: the error is there

```
NoMethodError (undefined method 'debug?' for nil)
Caused by: NoMethodError (undefined method 'debug?' for nil)
Information for: NoMethodError (undefined method 'debug?' for nil):
/rails/activesupport/lib/active_support/event_reporter/log_subscriber.rb:9:in 'block in '
/rails/activesupport/lib/active_support/event_reporter/log_subscriber.rb:47:in 'ActiveSupport::EventReporter::LogSubscriber#emit'
```