Allow passing a class to `dom_id`
You no longer need to call `new` when passing a class to `dom_id`.
This makes `dom_id` behave like `dom_class` in this regard.
Apart from saving a few keystrokes, it prevents Ruby from needing to
instantiate a whole new object just to generate a string.

Before:
```ruby
dom_id(Post) # NoMethodError: undefined method `to_key' for Post:Class
```

After:
```ruby
dom_id(Post) # "new_post"
```

You can still call `dom_id(Post.new)`.