Fix $LOAD_PATH to correctly require files
Other I would get errors like:

LoadError: cannot load such file -- rails/api/generator (LoadError)

We were loading the installed rails gem and not the current subdirectories

This can be reproduced by doing `bundle clean --force` then `rake`

Fixes #50739