Extract notes from files in binary
Prevents:

ArgumentError: invalid byte sequence in UTF-8
railties/lib/rails/source_annotation_extractor.rb:115:in `=~'
railties/lib/rails/source_annotation_extractor.rb:115:in `block in extract_annotations_from'

And there's no reason we need to interpret the files as UTF-8
when scanning for annotations.

Applies to Rails 4.2 as well.