Hi I tried: rake --trace db:create:all ==> undefined method `[]' for nil:NilClass /home/akt/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.1/lib/active_record/railties/databases.rake:31:in `block (4 levels) in <top (required)>'
Adding this patch, the error removed an the action worked.