Dont try to call method missing in routes if thats not what we want
If, doing a test like this:

```
class BugTest < ActionView::TestCase
  def test_foo
    omg
  end
```

Will raise with:
```
RuntimeError: In order to use #url_for, you must include routing helpers
explicitly. For instance, `include
Rails.application.routes.url_helpers`.
```

Thats a bit confusing, as we are not calling url_for at all.