Allow installing ruby platform gems for sass-embedded
In sass-contrib/sass-embedded-host-ruby@2c14553 support for Ruby < 3.2
was ended for native linux platform gem installs, because it has some
issues.

```
Installing sass-embedded 1.78.0 (was 1.76.0) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/sass-embedded-1.78.0/ext/sass
/home/zzak/.rbenv/versions/3.1.7/bin/ruby -I/home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0 -rrubygems
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/rake-13.3.0/exe/rake
RUBYARCHDIR\=/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.78.0
RUBYLIBDIR\=/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.78.0
gem install --force --install-dir /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/sass-embedded-1.78.0/ext/sass/ruby
--no-document --ignore-dependencies --platform x86_64-linux-gnu --version 1.78.0 sass-embedded
rake aborted!
NameError: uninitialized constant JSON::Fragment
<internal:/home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
<internal:/home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
<internal:/home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
<internal:/home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
<internal:/home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
<internal:/home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'

Caused by:
NoMethodError: undefined method `parse' for #<Psych::Parser:0x00007f813b85ead0
@handler=#<Psych::Handlers::DocumentStream:0x00007f813b85ebe8 @stack=[], @last=nil, @root=nil, @start_line=nil,
@start_column=nil, @end_line=nil, @end_column=nil, @block=#<Proc:0x00007f813b85eb20
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/psych.rb:399>>, @external_encoding=0>

      parser.parse yaml, filename
            ^^^^^^

Tasks: TOP => default => install => cli.rb => dart-sass
(See full trace by running task with --trace)
rm -rf /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/sass-embedded-1.78.0/ext/sass/ruby

rake failed, exit code 1

Gem files will remain installed in /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/sass-embedded-1.78.0 for
inspection.
Results logged to
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.78.0/gem_make.out

  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/ext/builder.rb:102:in `run'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/ext/rake_builder.rb:28:in `build'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/ext/builder.rb:171:in `build_extension'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/ext/builder.rb:205:in `block in build_extensions'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `each'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `build_extensions'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/3.1.0/rubygems/installer.rb:843:in `build_extensions'
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/rubygems_gem_installer.rb:76:in
`build_extensions'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/source/rubygems.rb:205:in `install'
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/installer/gem_installer.rb:54:in
`install'
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/installer/parallel_installer.rb:132:in
`do_install'
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/installer/parallel_installer.rb:123:in
`block in worker_pool'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/worker.rb:62:in `apply_func'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/worker.rb:54:in `loop'
  /home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/worker.rb:54:in `process_queue'
/home/zzak/.rbenv/versions/3.1.7/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/worker.rb:90:in `block (2 levels) in
create_threads'

An error occurred while installing sass-embedded (1.78.0), and Bundler cannot continue.

In Gemfile:
  dartsass-rails was resolved to 0.5.0, which depends on
    sass-embedded
```