Fix `NoMethodError` when content type is set to nil in tests
If an ActionController::TestCase test sets the request content type to
nil, Rails raises an obscure “undefined method 'to_sym' for nil” NoMethodError. This commit fixes the code so a clearer
“Unknown Content-Type” error is raised.

Co-authored-by: Jerome Dalbert <jerome.dalbert@gmail.com>