Fix async `ActiveRecord::StatementCache` execution with out-of-range bind values
The `Promise.wrap` method does not exist;
we should use `Promise::Complete.new` instead.

```
Error:
ActiveRecord::StatementCacheTest#test_out_of_range_bind_value_returns_an_empty_result_when_async:
NoMethodError: undefined method 'wrap' for class ActiveRecord::Promise
    lib/active_record/statement_cache.rb:159:in 'ActiveRecord::StatementCache#execute'
    test/cases/statement_cache_test.rb:132:in 'ActiveRecord::StatementCacheTest#test_out_of_range_bind_value_returns_an_empty_result_when_async'

bin/test test/cases/statement_cache_test.rb:125
```