Fix error in `ActiveRecord::Migration.check_pending!`
Since https://github.com/rails/rails/commit/e9d835f05a90d6da03f69e1ecb59bc3f38edb979 this method has not worked, it has failed with this error:

```
NoMethodError: undefined method `pending_migrations' for #<ActiveRecord::MigrationContext:0x00005598468f8e58>
Did you mean?  pending_migration_versions
```

I agree with Eileen that eventually we could deprecate it, but to get it working I just reversed the changes in https://github.com/rails/rails/commit/e9d835f05a90d6da03f69e1ecb59bc3f38edb979 and added a regression test.