Bump RuboCop to fix some transient failures
```
rubocop --parallel
Error: `Rails` cops have been extracted to the `rubocop-rails` gem.
(obsolete configuration found in .rubocop.yml, please update it)
````

Like here:
* https://buildkite.com/rails/rails/builds/120729/steps/canvas?sid=0198a576-b57c-485b-803a-150b40ee41df
* https://buildkite.com/rails/rails/builds/120724/steps/canvas?sid=0198a53d-2d42-49b2-8b35-97c2395f01b2

This is fixed since RuboCop 1.74 with https://github.com/rubocop/rubocop/pull/13954 but I can't tell why it would start only now.

`rubocop-md` needs a bump as well to silence some deprecation about a renamed cop.

Other changes are what rubocop now wants