Better error messages when association name is invalid in the argument of `ActiveRecord::QueryMethods::WhereChain#missing`
before:

```
Post.where.missing(:cars).to_a # Post does not have association named `cars`

=> NoMethodError: undefined method `table_name' for nil:NilClass
```

It is complicated message.

after:

```
Post.where.missing(:cars).to_a
=> ArgumentError: An association named `:cars` does not exist on the model `Post`.
```