Use __callee__ to pass alias instead of original method name
Before

```
> Article.left_joins
ArgumentError: The method .left_outer_joins() must contain arguments.
```

After

```
> Article.left_joins
ArgumentError: The method .left_joins() must contain arguments.
```