Exit status 3 when Action Cable integration tests fail due to Saucelabs error
This is to mitigate errors like:
https://buildkite.com/rails/rails/builds/107403#018f9917-fd63-4701-9620-f9caf2caaf2d/1163-1195

```
ERROR [karma-server]:
Error: [init({...}})] The environment you requested was unavailable.
```

We can make buildkite-config retry this status and soft-fail on exit 3.