Fix backported deprecation test for 7-0-stable
Follow-up to 0376f2238182abf575ea6ff00b9a1c1d74a5a43f.

This fixes the following error when running tests:

  ```
  DeprecationTest#test_warn_deprecation_can_blame_code_generated_with_eval:
  RuntimeError: Wrapped undumpable exception for: NoMethodError: undefined method `behavior=' for nil:NilClass
      rails/activesupport/test/deprecation_test.rb:945:in `block in <class:DeprecationTest>'
  ```

The `@deprecator` variable was added in 2b7c03e7b4ccba885d0da1ac20cd28b16e01469b
which was not backported to `7-0-stable`.