Fix missing require of reverse_merge extension
The private method `#raw_config` in `ConnectionUrlResolver` uses
`Hash#reverse_merge`, which is an `ActiveSupport` core extension.

This fixes an error

    NoMethodError: undefined method `reverse_merge' for {}:Hash

in code that uses `ActiveRecord` without having previously loaded the
`reverse_merge`.