Fix failing test due to active_model not loading
```
vscode ➜ /workspaces/rails/activerecord (main) $ bin/test test/cases/arel/select_manager_test.rb
```
Run the above test.
At that time, if this `require "active_model"` is not in `activerecord/lib/arel.rb`, the following error will occur
```
NameError: uninitialized constant Arel::Nodes::ActiveModel
    lib/arel/nodes/casted.rb:50:in `build_quoted'
    test/cases/arel/select_manager_test.rb:686:in `block (2 levels) in <class:SelectManagerTest>'
```

Maybe from [this change](https://github.com/rails/rails/pull/41577), the test is failing.