Skip test_via_to_sql_with_complicating_connection for PostgreSQL 19+
PostgreSQL 19 no longer allows setting standard_conforming_strings to OFF.

```sql
postgres=# SET standard_conforming_strings = off;
ERROR:  non-standard string literals are not supported
postgres=# select version();
                           version
--------------------------------------------------------------------
 PostgreSQL 19devel on x86_64-linux, compiled by gcc-15.2.1, 64-bit
(1 row)
```

According to #14632, the purpose of the failing test is to ensure that the unescape_bytea method is per-connection, not global.
Since PostgreSQL 19dev no longer allows setting standard_conforming_strings to OFF, the value will no longer vary per connection,
so  we can skip this test when the PostgreSQL version is 19 or higher.

Fix #56789