Fix ImplicitRender for BasicRendering
When using `BasicRendering` you're obligated to invoke render explicitly in action method.

Before that fix, if you had controller like this:

    class PagesController < ApplicationController
      def index
      end
    end

following error was raised:

    NoMethodError in PagesController#index

    undefined method `has_key?' for nil:NilClass

After this change user will be instructed what to do with clear message:

    ActionController::BasicRendering::NoRenderError in PagesController#index

    BasicRendering requires controller action to invoke `render` method explicitly,
    with :text or :nothing option. For more, you need to include ActionView.