Require 'active_support/deprecation' instead of 'active_support/deprecation/proxy_wrappers'
* Fix this error.
   * `NoMethodError: undefined method `instance' for ActiveSupport::Deprecation:Class`
* You can't call `ActiveSupport::Deprecation.instance` method including `Singleton` module.
   * So load `active_support/deprecation` file.