Missing require "AS/core_ext/date_time/conversions"
This causes
  "NameError: undefined local variable or method `nsec' for #<DateTime:0x0000559163cdd878>"