Add custom_message to ActiveModel::Error and helpers in ActiveModel::Errors
Use explicit keyword argument for to_hash
Fixup documentation for as_json
Fix error
Error:
ValidationsTest#test_errors_to_json:
ArgumentError: wrong number of arguments (given 1, expected 0)
    /rails/activemodel/lib/active_model/errors.rb:215:in `as_json'
    /rails/activesupport/lib/active_support/json/encoding.rb:35:in `encode'
    /rails/activesupport/lib/active_support/json/encoding.rb:22:in `encode'
    /rails/activesupport/lib/active_support/core_ext/object/json.rb:42:in `to_json'
    /rails/activemodel/test/cases/validations_test.rb:218:in `test_errors_to_json'

Update docs for as_jason and to_hash
Add custom_messages method
Reorder and document custom_message
Document lookup chain
Add generate_custom_message method
Support custom_message_for
Support the `message_method` keyword argument in as_json and to_hash
Introduce test to support previous not-nested syntax
Introduce message key for translations to support both message and custom_message
Implement all missing tests
Copy `generate_custom_message` and modify it to work the same as `message`
Allow lambda in messages and options values and i18n interpolation
Allow for singular/plural variants
Allow interpolation
Add custom message method