Rack responses may be frozen
We are getting errors like this in our production rails app from this
middleware:

     FrozenError: can't modify frozen Hash

I'm not sure where the frozen response is coming from, but it seems like
a thing which can happen -- even within rails, in
ActionDispatch::Http::Response#before_sending:

    def before_sending
      # Normally we've already committed by now, but it's possible
      # (e.g., if the controller action tries to read back its own
      # response) to get here before that. In that case, we must force
      # an "early" commit: we're about to freeze the headers, so this is
      # our last chance.
      commit! unless committed?

      headers.freeze
      request.commit_cookie_jar! unless committed?
    end

This middleware seems to take pains to avoid too much object churn, so
the spirit has been followed here to only duplicate what is required to
insert the header.