Use kwargs in Module#delegate
Since we started converting methods to use kwargs, I think that
`Module#delegate` can benefit from the treatment.

Now, we do lose a good message, IMO.

```ruby
>> module A
>>  delegate :foo
>> end
```

Used to produce:

```
ArgumentError: Delegation needs a target. Supply an options hash with a :to key as the last argument (e.g. delegate :hello, to: :greeter).
```

With this change the error is:

```
ArgumentError: missing keyword: to
```

However, I do think with time people will start using more and more
kwargs, the error will be quite familiar to most of the devs.