Add missing require for zlib
Zlib is used to generate the advisory lock since commit 2c2a8755460 .

Using the Migrator fails since then, when it is called without the rails context:

    NameError: uninitialized constant ActiveRecord::Migrator::Zlib

This patch fixes the above error.