Relocate require in AS::Deprecation
Without this, it's possible to encounter:
NoMethodError: undefined method `on_jruby?' for Concurrent:Module

See also https://github.com/ruby-concurrency/concurrent-ruby/pull/833