Allow BroadcastLogger to pass through kwargs
When BroadcastLogger is applied to a logger implementation that takes
kwargs, a developer invoking a logging message while passing kwargs will
run into

    ArgumentError: wrong number of arguments (given 2, expected 0..1)

This error is confusing since the 'correct' arguments are passed, and
BroadcastLogger's splat unexpectedly converts the kwargs into a hash
and passes that hash along as a second argument instead of forwarding
along the method arguments unchanged.