Ignore "gem "bundler" cannot be uninstalled because it is a default gem" error when tested with ruby-head
This pull request attempts to ignore the following error
when tested with ruby-head which has bundler as a default gem.

```ruby
$ rvm @global do gem uninstall bundler --all --ignore-dependencies --executables
ERROR:  While executing gem ... (Gem::InstallError)

    gem "bundler" cannot be uninstalled because it is a default gem

The command "rvm @global do gem uninstall bundler --all --ignore-dependencies --executables" failed and exited with 1 during .
```

Refer https://travis-ci.org/rails/rails/jobs/295600391

This workaround should be removed once https://github.com/bundler/bundler/issues/6072 is addressed.