Raise database error when table doesn't exist
Since 1944a7e74c6c1b7a6234414a00d294412c05fde1, adding a foreign key or
check constraint to a non-existent table results in an unhelpful error:

    NoMethodError: undefined method `scan' for nil:NilClass

This restores the previous behaviour of raising the underlying error
from the database, which describes the actual problem.