Fix activestorage usage with ExectJS / NodeJS
File and window are not defined when using ExecJS / NodeJS. This makes
it difficult to integrate this library with server side rendering
through packages like react-rails (need to skip or stub File / window).

Running when using:

node --eval "require('./assets/javascripts/activestorage.js')"

Before:

    Thrown:
    ReferenceError: File is not defined
        at /assets/javascripts/activestorage.js:438
        at /assets/javascripts/activestorage.js:2

After:

    { start: [Function: start], DirectUpload: [Function: DirectUpload] }