Addresses undefined local variable or method `connection' error
This commit addresses following error since 48a035712e9a4478ff248fd51ff43505d2aa2ddb merged.

```
  1) Error:
test_create_join_table_with_symbol_and_string(CopyMigrationsTest):
NameError: undefined local variable or method `connection' for #<CopyMigrationsTest:0x00000003df56a8>
    test/cases/migration_test.rb:760:in `test_create_join_table_with_symbol_and_string'
```